name: Run Gradle Builds
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
        cache: gradle
    - name: Run Pre-Commit
      uses: actions/setup-python@v3
      uses: pre-commit/action@v3.0.0
    - name: Run Gradle
      run: ./gradlew build
